AllCops:
  Include:
    - "**/Rakefile"
    - "**/config.ru"
    - "Gemfile"
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "spec/factories.rb"
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/IfUnlessModifier:
  Enabled: false

Style/PredicateName:
  NamePrefixBlacklist:
    - is_
    - have_

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/NumericLiterals:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: false
