services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
language: ruby
sudo: false
rvm:
- 2.4.0
env:
- RAILS_VERSION=5.0.2
branches:
  only:
  - master
install:
- bundle install
script:
- bundle exec rake db:reset
- bundle exec rake lint
- bundle exec rake spec