coverage:
  precision: 2
  round: down
  range: 50...100

  status:
    project:
      default:
        enabled: yes
        target: auto
        threshold: 5%
    patch:
      default:
        enabled: no
        target: 0%
