development: &default
  adapter: postgresql
  database: homewatch_development
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: homewatch_test

production:
  <<: *default
  database: homewatch
